### ISSUE TITLE
Add flux

### ISSUE THREAD

**Issue by vsoch** [snakemake/snakemake-plugin-catalog#2]
hey @johanneskoester what do we need to do to add flux here?

https://github.com/snakemake/snakemake-executor-plugin-flux

**Comment by johanneskoester** [comment]
Should be fixed and appear soon. THere is an error with the kueue plugin which caused all subsequent plugins to not being processed. The scraper is more robust now and should work again. Also check the note on this here: https://github.com/snakemake/snakemake-plugin-catalog/commit/0b1b2430a39af9c9f9cb34b41ad6190cbd2bdc29

**Comment by johanneskoester** [comment]
Please contact me via discord if it still fails.
